/*
 * Zentral Vet Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type AnimalEntry struct {
	Id              int32                   `json:"id,omitempty"`
	Name            string                  `json:"name,omitempty"`
	OwnershipLimits *HusbandryRuleType      `json:"ownershipLimits,omitempty"`
	OwnershipLaw    *AnimalRegistrationType `json:"ownershipLaw,omitempty"`
	Registered      *time.Time              `json:"registered,omitempty"`
	ExpectedMaxAge  int32                   `json:"expectedMaxAge,omitempty"`
}
