/*
 * Zentral Vet Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AnimalRegistrationType string

// List of AnimalRegistrationType
const (
	PET_AnimalRegistrationType    AnimalRegistrationType = "Pet"
	EXOTIC_AnimalRegistrationType AnimalRegistrationType = "Exotic"
)
