/*
 * Zentral Vet Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type HusbandryRuleType string

// List of HusbandryRuleType
const (
	UNLIMITED_HusbandryRuleType             HusbandryRuleType = "Unlimited"
	REGISTRATION_REQUIRED_HusbandryRuleType HusbandryRuleType = "RegistrationRequired"
	PERMISSION_REQUIRED_HusbandryRuleType   HusbandryRuleType = "PermissionRequired"
	FORBIDDEN_HusbandryRuleType             HusbandryRuleType = "Forbidden"
)
