/*
 * Zentral Vet Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse201 struct {
	CreatedId int32  `json:"createdId,omitempty"`
	Name      string `json:"name,omitempty"`
}
