openapi: "3.0.2"
info:
  title: Vet Health
  version: "1.0"
servers:
  - url: https://api.server.test/v1
paths:
  /vaccination/{type}:
    get:
      tags:
      - vaccination
      summary: Show an vaccination
      description: get vaccination by animal type
      parameters:
      - name: type
        in: path
        description: Animal type
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vaccination'
    post:
      tags:
      - vaccination
      summary: Adds an vaccination
      description: adds vaccination by animal type if animal is a Pet
      parameters:
      - name: type
        in: path
        description: Animal type
        required: true
        schema:
          type: string
      requestBody:
        description: query params
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vaccination'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vaccination'
      x-codegen-request-body-name: reqest
components:
  schemas:
    Vaccination:
      type: object
      properties:
        name:
          type: string
          description: Name of the vaccination
        vakzinationdate:
          type: string
          description: Date when the vaccination was done
          format: date
          example: 2021-10-18T14:16:00Z
