package router

import (
	"vet-health-golang/controller"

	"github.com/gin-gonic/gin"

	_ "vet-health-golang/docs"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	// "vet-health-golang/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title           Swagger Example API
// @version         2.0
// @description     This is a sample server celler server.
// @termsOfService  http://swagger.io/terms/

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /api/v1
func InitRouter() {

	router := gin.Default()

	router.Use(gin.Logger())
	router.Use(gin.Recovery())

	v1 := router.Group("/api/v1/health")
	{
		vakzin := v1.Group("/vakzin")
		{
			vakzin.GET(":id", controller.GetVazinById)
			vakzin.POST(":id", controller.AddVazination)
		}
	}

	//router.GET("/ping/:animalid", controller.GetPong)
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	router.Run()
}
